// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// resampling_test_impl
double resampling_test_impl(NumericVector x, NumericVector y, long nmax);
RcppExport SEXP _proDD_resampling_test_impl(SEXP xSEXP, SEXP ySEXP, SEXP nmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< long >::type nmax(nmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(resampling_test_impl(x, y, nmax));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_proDD_resampling_test_impl", (DL_FUNC) &_proDD_resampling_test_impl, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_proDD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
